# -*- mode: org; -*-
#+TITLE: README
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Mar 01 19:11:36 MSK 2023>
# Time-stamp: <Последнее обновление -- Wednesday March 8 15:31:21 MSK 2023>


Урок с канала [[https://www.youtube.com/@FreelancerLifeStyle][Фрілансер по життю]].

Рассказывает Женя Андриканич.

Ссылка на сам видеоурок [[https://www.youtube.com/watch?v=PqTrhfjLQBI][
Отправка формы на почту. Верстка валидация и отправка формы без перезагрузки. AJAX. PHPMailer.]]

Сам урок из плейлиста [[https://www.youtube.com/playlist?list=PLM6XATa8CAG4uCli-pMvuvwj46UaQoqIc][Все об HTML - верстке сайтов (Front End) // Уроки гайды]].

** Описание (взято из описания видео на ютубе):

   Отправка формы на почту очень частая задача при разработке любого сайта. Особенно популярна форма на
   лендинг. Конечно же при этом форму нужно красиво сверстать, а также особым образом валидировать поля
   формы. Поэтому в этом выпуске я решил показать как сделать все это сразу используя HTML CSS
   JavaScript и плагин PHP PHPMailer. Ты научишься верстать и стилизовать различные элементы форм такие
   как checkbox radio select button file и другие. Добавим крутую фишку превью для загружаемой
   фотографии. Сделаем валидацию полей в том числе e-mail. И, с помощью JavaScript технологии AJAX
   (fetch), без перезагрузки страницы отправим форму на почту, настроив при этом плагин PHPMailer.

** От себя немного:

   Так как я не являюсь его патроном (халявщик, одним словом), доступа к его проекту у меня нет,
   пишу всё с экрана и от себя, если чего не увидел.
